# docker dompose for aws
version: "3.1"

services: 
  db: 
    image: mysql:8.0.28
    container_name: mysql_zimssaza_prod
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "6033:3306"
    environment:
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-test:/var/lib/mysql
      - ./init.sql:/data/application/init.sql